### ISSUE TITLE
No /drone topics published

### ISSUE THREAD

**Issue by hydro806** [FIRAAir/FIRA-Air-Simulator#1]
Can someone help me? 
I have followed all the installation instructions. When I try to run the run.sh script, the gazebo opens. But when I check rostopics I can't find the /drone topic published. 
![Screenshot from 2022-07-25 06-41-53](https://user-images.githubusercontent.com/110006818/180918632-466b4095-d72c-4e13-a67f-9045b51cb82e.png)
So I cant controll the drone. Where is my mistake? Thanks for help

**Comment by FurryWaifu** [comment]
If you launch the gazebo sim with SITL, you have only gazebo nothing on ROS. Please follow ros tutorials to connect ros to SITL

**Comment by Zufaruu** [comment]
yeah having the sama issue here

**Comment by 10account** [comment]
> 

Hi there, i've been googling on the topics about this but found nothing satifying. Would you be kind enough to put link or some sort of source on how to do that please?, It will be much appriciated

**Comment by 10account** [comment]
> If you launch the gazebo sim with SITL, you have only gazebo nothing on ROS. Please follow ros tutorials to connect ros to SITL

Hi there, i've been googling on the topics about this but found nothing satifying. Would you be kind enough to put link or some sort of source on how to do that please?, It will be much appriciated

**Comment by 10account** [comment]
> > If you launch the gazebo sim with SITL, you have only gazebo nothing on ROS. Please follow ros tutorials to connect ros to SITL
> 
> Hi there, i've been googling on the topics about this but found nothing satifying. Would you be kind enough to put link or some sort of source on how to do that please?, It will be much appriciated

I found the solutions, turns out somehow you need to load the drone and the world in one launch file, then the drone's topic will appear

**Comment by FIRAAir** [comment]
Hello. 

The problem is fixed in the new version (Version 1.1.1). And you should be able to access all the topics.

<img width="505" alt="Screen Shot 2022-08-06 at 3 53 00 AM" src="https://user-images.githubusercontent.com/92919423/183222976-bf4e9288-3f73-4576-984f-1f7cf429e0af.png">
