### ISSUE TITLE
Quadcopter do not appear after roslaunch sjtu_drone start.launch.

### ISSUE THREAD

**Issue by ongkeantuan12** [FIRAAir/FIRA-Air-Simulator#1]
![image](https://user-images.githubusercontent.com/59481195/144162074-91176e03-e5c5-4923-b061-ebdde2a5d9c8.png)
![image](https://user-images.githubusercontent.com/59481195/144162183-8aaf8c87-4a17-4887-a60b-e8b496063a21.png)

Hi there, I have a issue about the gazebo quadcopter... the quadcopter sometime did not appear after every launching. Please help me to solve the issue. Thanks in advance.

**Comment by FIRAAir** [comment]
Hello.
Thanks for the feedback. Fixed in the updated version of the simulator. 
7b7f773a0d171899e82dffe2f4c91ddcb90c7854
