### ISSUE TITLE
Gate color still white

### ISSUE THREAD

**Issue by hydro806** [FIRAAir/FIRA-Air-Simulator#2]
Hello, in the rules gate are colored magenta, but in the simulation still white

**Comment by Benedixx** [comment]
hello there, regarding the color of the gate, you can edit the blend file using blender software

**Comment by FurryWaifu** [comment]
> Hello, in the rules gate are colored magenta, but in the simulation still white

Hello there, regarding the color of the gate, you can edit the blend file using blender software

**Comment by FIRAAir** [comment]
Hello. 

Thanks for your feedback. The color for the frame of the gate is changed in the new version (Version 1.1.1).
